<<HOL message: Created theory "aclfoundation">>
Saved theorem _____ "EQ_WeakOrder"
Saved theorem _____ "WeakOrder_Exists"
Saved theorem _____ "po_bij"
Saved theorem _____ "abs_po11"
Saved theorem _____ "onto_po"
Saved theorem _____ "absPO_fn_onto"
Saved theorem _____ "PO_repPO"
Saved theorem _____ "WO_repPO"
Saved theorem _____ "repPO_iPO_partial_order"
Saved definition __ "one_weakorder_def"
Saved theorem _____ "one_weakorder_WO"
Saved definition __ "O1_def"
Saved theorem _____ "repPO_O1"
Saved theorem _____ "RPROD_THM"
Saved theorem _____ "refl_prod_refl"
Saved theorem _____ "trans_prod_trans"
Saved theorem _____ "antisym_prod_antisym"
Saved theorem _____ "WO_prod_WO"
Saved definition __ "prod_PO_def"
Saved theorem _____ "repPO_prod_PO"
Saved theorem _____ "SUBSET_WO"
Saved definition __ "Subset_PO_def"
Saved theorem _____ "repPO_Subset_PO"
Saved theorem _____ "datatype_Princ"
Saved theorem _____ "Princ_11"
Saved theorem _____ "Princ_distinct"
Saved theorem _____ "Princ_case_cong"
Saved theorem _____ "Princ_nchotomy"
Saved theorem _____ "Princ_Axiom"
Saved theorem _____ "Princ_induction"
Saved theorem _____ "IntLevel_11"
Saved theorem _____ "IntLevel_distinct"
Saved theorem _____ "IntLevel_case_cong"
Saved theorem _____ "IntLevel_nchotomy"
Saved theorem _____ "IntLevel_Axiom"
Saved theorem _____ "IntLevel_induction"
Saved theorem _____ "SecLevel_11"
Saved theorem _____ "SecLevel_distinct"
Saved theorem _____ "SecLevel_case_cong"
Saved theorem _____ "SecLevel_nchotomy"
Saved theorem _____ "SecLevel_Axiom"
Saved theorem _____ "SecLevel_induction"
<<HOL message: Defined types: "Princ", "IntLevel", "SecLevel">>
Saved theorem _____ "datatype_Form"
Saved theorem _____ "Form_11"
Saved theorem _____ "Form_distinct"
Saved theorem _____ "Form_case_cong"
Saved theorem _____ "Form_nchotomy"
Saved theorem _____ "Form_Axiom"
Saved theorem _____ "Form_induction"
<<HOL message: Defined type: "Form">>
Saved theorem _____ "datatype_Kripke"
Saved theorem _____ "Kripke_11"
Saved theorem _____ "Kripke_case_cong"
Saved theorem _____ "Kripke_nchotomy"
Saved theorem _____ "Kripke_Axiom"
Saved theorem _____ "Kripke_induction"
<<HOL message: Defined type: "Kripke">>
Saved definition __ "intpKS_def"
Saved definition __ "jKS_def"
Saved definition __ "imapKS_def"
Saved definition __ "smapKS_def"
Saved theorem _____ "KS_bij"
Exporting theory "aclfoundation" ... done.
Theory "aclfoundation" took 1.4s to build
Completed load of aclfoundationScript
